---
- name: Update Message-of-the-Day
  template:
    src: motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Remove cloud-init
  apt:
    name: cloud-init
    state: absent
    force_apt_get: true
  become: true

- name: Remove cloud-init local data
  file:
    path: /etc/cloud
    state: absent
  become: true

- name: Remove cloud-init system data
  file:
    path: /var/lib/cloud
    state: absent
  become: true

- name: Ensure configuration management script exists
  template:
    src: pull-config.j2
    dest: /usr/local/bin/pull-config
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Ensure ansible-pull cronjob exists
  cron:
    name: Ensure ansible-pull cronjob exists
    minute: "1"
    job: /usr/local/bin/pull-config system 2>&1 > /tmp/cron-pull-config-system

- name: Ensure silent boot is disabled in GRUB
  template:
    src: grub.j2
    dest: /etc/default/grub
    owner: root
    group: root
    mode: '0644'
  become: true
  notify:
    - Update GRUB


- name: Ensure GNOME site-wide settings directory exists
  file:
    path: /etc/dconf/db/site.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Ensure GNOME site-wide locks directory exists
  file:
    path: /etc/dconf/db/site.d/locks
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Ensure GNOME profile directory exists
  file:
    path: /etc/dconf/profile
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Ensure GNOME site-wide settings will be loaded
  template:
    src: dconf-profile.j2
    dest: /etc/dconf/profile/user
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Ensure GNOME site-wide settings are configured
  template:
    src: dconf-db.j2
    dest: /etc/dconf/db/site.d/ansible
    owner: root
    group: root
    mode: '0644'
  become: true
# notify:
#   - "Apply GNOME configuration"

- name: Ensure GNOME site-wide settings are locked down
  template:
    src: dconf-locks.j2
    dest: /etc/dconf/db/site.d/locks/ansible
    owner: root
    group: root
    mode: '0644'
  become: true
# notify:
#   - "Apply GNOME configuration"

- name: Ensure automatic updates are enabled
  apt:
    - name: unattended-upgrades
    - state: latest 
  become: true

- name: Ensure automatic updates are configured
  template:
    src: autoupdates.j2
    dest: /etc/apt/apt.conf.d/88autoupdate-rgmc
    owner: root
    group: root
    mode: '0644'
  become: true