---
- name: Update motd
  template:
    src: "motd.j2"
    dest: "/etc/motd"
    owner: "root"
    group: "root"
    mode: "0644"
  become: true

- name: "Update bashrc: colour prompt"
  lineinfile:
    path: "/etc/bash.bashrc"
    regexp: "force_color_prompt=yes"
    line: "force_color_prompt=yes"
    state: present
    insertafter: EOF
  when: basics_colorprompt | bool
  become: true

- name: Remove cloud-init
  apt:
    name: cloud-init
    state: absent
    force_apt_get: true
  become: true

- name: Remove cloud-init local data
  file:
    path: /etc/cloud
    state: absent
  become: true

- name: Remove cloud-init system data
  file:
    path: /var/lib/cloud
    state: absent
  become: true

- name: Ensure ansible-pull cronjob exists
  cron:
    name: "Ensure ansible-pull cronjob exists"
    minute: "7"
    hour: "3"
    job: "/usr/bin/ansible-pull -i host -U https://github.com/oskar-fagerfjall/rgmc-cws main.yml 2&>1 > /tmp/cron-ansiblepull"

- name: Ensure silent boot is disabled in GRUB
  template:
    src: "grub.j2"
    dest: "/etc/default/grub"
    owner: "root"
    group: "root"
    mode: "0644"
  become: true
  notify:
    - "Update GRUB"

- name: Ensure GNOME loads site-wide settings
  template:
    src: "dconf-profile.j2"
    dest: "/etc/dconf/profile/user"
    owner: "root"
    group: "root"
    mode: "0644"
  become: true

- name: Install site-wide GNOME configuration
  template:
    src: "dconf-db.j2"
    dest: "/etc/dconf/db/site.d/ansible"
    owner: "root"
    group: "root"
    mode: "0644"
  become: true
  notify:
    - "Apply GNOME configuration"

- name: Lock down certain GNOME settings
  template:
    src: "dconf-locks.j2"
    dest: "/etc/dconf/db/site.d/locks/ansible"
    owner: "root"
    group: "root"
    mode: "0644"
  become: true
  notify:
    - "Apply GNOME configuration"

