---
- name: Update motd
  template:
    src: "motd.j2"
    dest: "/etc/motd"
    owner: "root"
    group: "root"
    mode: "0644"
  become: true

- name: "Update bashrc: colour prompt"
  lineinfile:
    path: "/etc/bash.bashrc"
    regexp: "force_color_prompt=yes"
    line: "force_color_prompt=yes"
    state: present
    insertafter: EOF
  when: basics_colorprompt | bool
  become: true

- name: Remove cloud-init
  apt:
    name: cloud-init
    state: absent
    force_apt_get: true
  become: true

- name: Remove cloud-init local data
  file:
    path: /etc/cloud
    state: absent
  become: true

- name: Remove cloud-init system data
  file:
    path: /var/lib/cloud
    state: absent
  become: true

- name: Ensure ansible-pull cronjob exists.
  cron:
    name: "Ensure ansible-pull cronjob exists"
    minute: "7"
    hour: "3"
    job: "/usr/bin/ansible-pull -i host -U https://github.com/oskar-fagerfjall/rgmc-cws main.yml 2&>1 > /tmp/cron-ansiblepull"