---
- name: Update GRUB
  command: update-grub
  become: true

#
# Applying the dconf config causes firefox to minimize. Restart computer instead. 
#
#- name: Apply GNOME configuration
#  command: dconf update
#  become: true