- name: Ensure ansible-repo is added
  apt_repository:
    repo: ppa:ansible/ansible
  become: true

- name: Ensure ansible is installed
  apt:
    name: ansible
    state: latest 
  become: true

- name: Ensure ansible site-wide inventory is configured
  template:
    src: inventory.j2
    dest: /etc/ansible/hosts
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Ensure ansible site-wide configuration is in place
  template:
    src: ansible.cfg.j2
    dest: /etc/ansible/ansible.cfg
    owner: root
    group: root
    mode: '0644'
  become: true
